### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by AL3XPI** [iiFlamiinBlaze/BlazinFly#14]
I give myself the permission fly.command and when i deop myself I'm not able to fly still. It gives me this error: 
![image](https://user-images.githubusercontent.com/35903333/61982583-3db4ed00-afcb-11e9-90c6-da269fdccab1.png)
Pocketmine 3.9.2 Bedrock 1.12.0 BlazinFly 1.8.7. Please help.

**Comment by iiFlamiinBlaze** [comment]
blazinfly.command is the new permission. Poggit made me change it to be able to submit it. Sorry for the inconvenience.

**Comment by AL3XPI** [comment]
oh ok. Thanks for the quick response.

**Comment by DimsWicks** [comment]
i give my member on my server permission blazinfly.command not working
pocketmine 3.11.1 bedrock 1.14.1

**Comment by ghost** [comment]
The problems wasn't fixed, you are hiding that bug or plugin problem.

**Comment by iiFlamiinBlaze** [comment]
Yes it is fixed, I have tested all my open source plugins myself. The new permissions are `blazinfly.command` and `blazinfly.other`
