### ISSUE TITLE
Problem BlazinFly

### ISSUE THREAD

**Issue by SHINIGAMILEOPV** [iiFlamiinBlaze/BlazinFly#16]
After uploading to the server, everyone can fly and the command works only when you fly to fall and fly can continue even after removing the plug from the server how to fix it?

**Comment by iiFlamiinBlaze** [comment]
You must have another fly plugin enabled on your server. Can you send a list of your enabled plugins by running /plugins in-game?

**Comment by SHINIGAMILEOPV** [comment]
PureEntitiesX v0.6.3, WorldGuard v1.0.3, essentialsTP v1.2.2, SeeDevice v0.0.7, WorldProtect v2.3.8, Repair v1.0.1, AutoClearLagg v3.0.0, SimpleHome v1.0.3, PurePerms v1.4.3, KeepInventory v1.0, CrashFixer v1, InvSee v1.0.0, BuilderTools v1.2.0-beta2, VanishV2 v1.4, ModSpectate v0.0.1, Festival v2.1.1, PureChat v1.4.11

**Comment by sqrrrrl** [comment]
my plugin lol
