### ISSUE TITLE
Request, flying in spawn world for vip ranks

### ISSUE THREAD

**Issue by artulloss** [iiFlamiinBlaze/BlazinFly#2]
I am requesting a feature:
flying in spawn world for vip ranks

**Comment by iiFlamiinBlaze** [comment]
Would you want full multi-world support?

**Comment by artulloss** [comment]
Doesn't need it, but would be cool if you could choose which worlds it works in ig lol

**Comment by iiFlamiinBlaze** [comment]
K I will add full multi-world support. Thanks for the suggestion! 😄

**Comment by iiFlamiinBlaze** [comment]
Closing this issue since I just implemented it in that commit ^^

**Comment by artulloss** [comment]
Thank you ✨
