### ISSUE TITLE
no fly pvp

### ISSUE THREAD

**Issue by benzodoesdev** [iiFlamiinBlaze/BlazinFly#7]
Does this support cobat logger?

**Comment by iiFlamiinBlaze** [comment]
“Cobat logger”? I prosome you mean combat logger, and what does fly have to do with combat logger...

**Comment by iZeaoGamer** [comment]
I think he means does this plugin support Combat Logger? As in will it work with Combat logger as well? But I assume it is supported, but I guess that's something you could answer to before this issue get's locked. (If this issue has been answered to.)

**Comment by iiFlamiinBlaze** [comment]
We do not support outside plugins, talk to the combat logger plugin developer if you want something changed.
